name: app-react
on: [push]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependeciens
        run: npm install


  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploying to production..."
